#!/bin/bash
# How to pair:
# more: https://wiki.archlinux.org/index.php/Bluetooth
# $ bluetoothctl
# > power on
# > scan on
# > agent on
# > pair <MAC>
# > agent off
# > scan off

nap_addrs=()
nap_names=()
while read line
do
    name="${line% *}"
    addr="${line##* }"
    addr="${addr#\(}"
    addr="${addr%\)}"
    if bt-device "--info=$addr"| grep -q 'NAP,'; then
        nap_addrs+=("$addr")
        nap_names+=("$name")
    fi
done < <(bt-device --list | grep -vF 'Added devices:')

number_of_nap=${#nap_addrs[@]}

if [ x"$1" = x"off" ]; then
    echo ""
    echo "ifdown bnep0"
    echo ""
    #sudo ifdown bnep0
    echo ""
    for i in $(seq 0 "$((number_of_nap-1))")
    do
        bt-device "--disconnect=${nap_addrs[$i]}"
    done
    echo ""
    ip addr
    exit
fi

if [ "$number_of_nap" -eq 0 ]; then
    echo "No NAP device paired, exiting."
    exit 1
elif [ "$number_of_nap" -eq 1 ]; then
    selected_nap=0
else
    echo "Available NAP devices:"
    echo ""
    for i in $(seq 0 "$((number_of_nap-1))")
    do
        echo "$i ${nap_addrs[$i]} ${nap_names[$i]}"
    done
    echo ""
    read -p "Select[0-$((number_of_nap-1))]: " selected_nap
fi

nap_addr=${nap_addrs[$selected_nap]}
nap_name=${nap_names[$selected_nap]}

echo ""
echo "Connecting to ${nap_addr} ${nap_name}"
echo ""

dbus-send --system --type=method_call --dest=org.bluez "/org/bluez/hci0/dev_${nap_addr//:/_}" org.bluez.Network1.Connect string:'nap'

echo -n 'Wait for bnep0 device'
while ! ip addr show dev bnep0 >& /dev/null
do
    echo -n '.'
    sleep 0.5
done
echo ""
echo ""
sleep 1

sudo busybox udhcpc -i bnep0 -f -q
#sudo ifup bnep0

# (sleep 2; sudo ifup bnep0) &
# journalctl -n 0 -f /sbin/dhclient
