#!/usr/bin/ruby

require 'fileutils'

videos = ARGV.select do |file|
  file =~ /\.(mp4|mkv)$/
end
if videos.size == 0
  videos = Dir.glob('*.{mp4,mkv}')
end

subtitles = ARGV.select do |file|
  file =~ /\.(ass|srt|ssa)$/
end
if subtitles.size == 0
  subtitles = Dir.glob('*.{ass,srt,ssa}')
end

subtitles.each do |subtitle|
  if subtitle =~ /(s\d+)?[^\d](?<episode>\d{2})[^\d]/i
    episode = $~[:episode]
    matched_videos = videos.select do |video|
      video =~ Regexp.new("[^\d]#{episode}[^\d]")
    end
    if matched_videos.size > 0
      matched_video = matched_videos[0]
      dirname = File.dirname(matched_video)
      basename = File.basename(matched_video, '.*')
      subtitle_ext = File.extname(subtitle)
      wanted_subtitle = File.join(dirname, basename) + subtitle_ext
      FileUtils.mv(subtitle, wanted_subtitle)
    end
  end
end
