#!/bin/bash

set -e

DATE="$(date +%Y%m%d%H%M)"
LABEL="Sony_RX100"

mkdir -p ~/Pictures/logs
cd ~/Pictures

do_sync() {
    echo "sync:"
    rsync "$@" --out-format='%i %n' -a "/media/$LABEL/" "$LABEL/" \
        | tee "logs/sync-$DATE-full.log" \
        | awk -W interactive '$1 == ">f+++++++++" && $NF ~ /\.(JPG|MP4)$/ {print "'$LABEL'/" substr($0,13)}' \
        | tee "logs/sync-$DATE-changed.log"
    echo
    ln -sf "sync-$DATE-changed.log" logs/changed.log
}

do_umount() {
    local dir
    for dir in /media/PMHOME "/media/$LABEL"
    do
        if [ -d "$dir" ]
        then
            udevil umount "$dir"
        fi
    done
}

do_upload() {
    local changed
    changed="$(readlink -f logs/changed.log)"
    if [ -s "$changed" ]
    then
        gphotos -l "$changed"
        mv "$changed" "${changed/changed/uploaded}"
    else
        echo "No new files to upload."
    fi
}

if [ -d "/media/$LABEL" ]
then
    do_sync
    do_umount
fi
do_upload
