#!/bin/sh
path="$(while read -r _ path _
do
    case "$path" in
        /media/$USER/*)
            echo "$path"
        ;;
    esac
done < /proc/mounts | dmenu -p umount)"

case "$path" in
    "/media/$USER/sshfs")
        fusermount -u "$path"
        ;;
    *)
        udevil umount "$path"
        ;;
esac

if [ $? -gt 0 ]
then
  notify-send 'Umount failed' "$path"
fi
