#!/bin/sh
iface="$(find /sys/class/net -mindepth 1 -maxdepth 1 -name 'wl*' -printf "%P\n" | head -n 1)"
WPA="/sbin/wpa_cli -i $iface"
if [ -z "$iface" ]
then
    echo "No wireless interface found"
    exit 1
fi

case "$1" in
    r)
        $WPA disconnect
        $WPA reconnect
        ;;
esac

$WPA
