#!/bin/bash

web () {
  url=$1
  shift

  # run cmds in tmux
  first_cmd=$1
  shift
  tmux new-session -d "$first_cmd"
  for cmd in "$@"; do
    tmux new-window "$cmd"
  done

  # i3 layout
  i3-msg 'workspace 6; append_layout .i3/webdev.json'

  # start firefox
  firefox -no-remote -P dev "$url" >&/dev/null &

  # vim
  gvim . &

  # terminal
  x-terminal-emulator -e tmux attach-session
}

guard () {
  web . guard
}

nanoc () {
  web http://localhost:3000 "nanoc view" guard
}

awestruct () {
  web http://localhost:4242 "awestruct -d --livereload"
}

action=$1
test -z "$action" && action="guard"

usage () {
  echo "USAGE: $(basename "$0") subcommand"
  echo
  echo "SUBCOMMANDS:"
  for cmd in $(compgen -A function | grep -v '^_')
  do
    echo "  $cmd"
  done
}

if [ x"$(type -t "$action")" == x"function" ]; then
  shift
  "${action}" "$@"
else
  usage
fi
