#!/bin/bash

web () {
  url=$1
  shift

  # run cmds in tmux
  first_cmd=$1
  shift
  tmux new-session -d "$first_cmd"
  for cmd in "$@"; do
    tmux new-window "$cmd"
  done

  # start firefox
  i3-msg split h
  firefox -no-remote -P dev "$url" >&/dev/null &

  # move/resize firefox
  sleep 2
  i3-msg resize grow width 10 px or 10 ppt

  # vim
  i3-msg focus left
  i3-msg split v
  gvim . &
  sleep 1
  i3-msg resize grow height 10 px or 30 ppt

  tmux attach-session
}

guard () {
  web . guard
}

nanoc () {
  web http://localhost:3000 "nanoc view" guard
}

awestruct () {
  web http://localhost:4242 "awestruct -d --livereload"
}

action=$1
test -z "$action" && action="guard"

usage () {
  echo "USAGE: $(basename "$0") subcommand"
  echo
  echo "SUBCOMMANDS:"
  for cmd in $(compgen -A function | grep -v '^_')
  do
    echo "  $cmd"
  done
}

if [ x"$(type -t "$action")" == x"function" ]; then
  shift
  "${action}" "$@"
else
  usage
fi
